#!/usr/bin/env ruby

require 'thor'

class Configurator < Thor
  include Thor::Actions

  def self.source_root
    File.dirname(__FILE__)
  end

  desc "hoe", "Copies the hoe_templates stuff to ~/.hoe_template"
  method_options force: false
  def hoe
    default_dir = "/.hoe_template"
    destination_root = Dir.home + default_dir

    if yes?("Copy to ~/.hoe_template?")
      remove_dir destination_root if options[:force]
      directory("hoe_template", Dir.home + default_dir)
    end
  end
end

Configurator.start

