#!/usr/bin/env ruby

require 'thor'

class Configurator < Thor
  include Thor::Actions

  def self.source_root
    File.dirname(__FILE__)
  end

  desc "hoe", "Copies the hoe_templates stuff to ~/.hoe_template"
  method_options force: false
  def hoe
    default_dir = "/.hoe_template"
    destination_root = Dir.home + default_dir

    if yes?("Copy to ~/.hoe_template?")
      remove_dir destination_root if options[:force]
      directory("hoe_template", Dir.home + default_dir)
    end
  end

  desc "git", "Sets up Steve's git config"
  def git
    puts "Setting up your git stuff now..."

    `git config --global user.name "Steve Loveless"`
    `git config --global user.email "steve.loveless@gmail.com"`
    `git config --global core.editor vim`
    `git config --global alias.ci 'commit'`
    `git config --global alias.st 'status'`
    `git config --global color.ui true`

    `git config --global merge.tool vimdiff`
    `git config --global diff.tool vimdiff`
    `git config --global difftool.prompt false`

    puts "Done.  Have you configured your SSH keys?"
  end
end

Configurator.start

